name: front_end
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  flutter_svg_provider: ^0.1.11
  http: ^0.13.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  rxdart: ^0.27.2

dev_dependencies:  
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/env/.env_dev
    - assets/img/
    - assets/utils/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
